cd debug
ruby frl.dependency.vendors.opc_foundation.debug.rb
ruby frl.lib.debug.rb
ruby frl.test.fs_fn.debug.rb
ruby frl.test.os_win32_registry.debug.rb
ruby frl.test.lexical_cast.debug.rb
ruby frl.test.logging.debug.rb
ruby frl.test.opc_address_space.debug.rb
ruby frl.test.opc_write_event_subscribe.debug.rb
ruby frl.test.opc_test.debug.rb
ruby frl.test.poor_xml.debug.rb
ruby frl.test.smart_ptr.debug.rb
ruby frl.test.psoi2_sender.debug.rb
ruby frl.projects.psoi2.debug.rb
cd ..
