cd release
ruby frl.dependency.vendors.opc_foundation.release.rb
ruby frl.lib.release.rb
ruby frl.test.fs_fn.release.rb
ruby frl.test.io_win32_registry.release.rb
ruby frl.test.lexical_cast.release.rb
ruby frl.test.logging.release.rb
ruby frl.test.opc_address_space.release.rb
ruby frl.test.opc_test.release.rb
ruby frl.test.poor_xml.release.rb
ruby frl.test.smart_ptr.release.rb
ruby frl.test.psoi2_sender.debug.rb
ruby frl.projects.psoi2.release.rb
cd ..
